#pragma once

typedef enum
{
	KEY_SCANCODE_UNKNOWN = 0,

	/**
	*  \name Usage page 0x07
	*
	*  These values are from usage page 0x07 (USB keyboard page).
	*/
	/* @{ */

	KEY_SCANCODE_A = 4,
	KEY_SCANCODE_B = 5,
	KEY_SCANCODE_C = 6,
	KEY_SCANCODE_D = 7,
	KEY_SCANCODE_E = 8,
	KEY_SCANCODE_F = 9,
	KEY_SCANCODE_G = 10,
	KEY_SCANCODE_H = 11,
	KEY_SCANCODE_I = 12,
	KEY_SCANCODE_J = 13,
	KEY_SCANCODE_K = 14,
	KEY_SCANCODE_L = 15,
	KEY_SCANCODE_M = 16,
	KEY_SCANCODE_N = 17,
	KEY_SCANCODE_O = 18,
	KEY_SCANCODE_P = 19,
	KEY_SCANCODE_Q = 20,
	KEY_SCANCODE_R = 21,
	KEY_SCANCODE_S = 22,
	KEY_SCANCODE_T = 23,
	KEY_SCANCODE_U = 24,
	KEY_SCANCODE_V = 25,
	KEY_SCANCODE_W = 26,
	KEY_SCANCODE_X = 27,
	KEY_SCANCODE_Y = 28,
	KEY_SCANCODE_Z = 29,

	KEY_SCANCODE_1 = 30,
	KEY_SCANCODE_2 = 31,
	KEY_SCANCODE_3 = 32,
	KEY_SCANCODE_4 = 33,
	KEY_SCANCODE_5 = 34,
	KEY_SCANCODE_6 = 35,
	KEY_SCANCODE_7 = 36,
	KEY_SCANCODE_8 = 37,
	KEY_SCANCODE_9 = 38,
	KEY_SCANCODE_0 = 39,

	KEY_SCANCODE_RETURN = 40,
	KEY_SCANCODE_ESCAPE = 41,
	KEY_SCANCODE_BACKSPACE = 42,
	KEY_SCANCODE_TAB = 43,
	KEY_SCANCODE_SPACE = 44,

	KEY_SCANCODE_MINUS = 45,
	KEY_SCANCODE_EQUALS = 46,
	KEY_SCANCODE_LEFTBRACKET = 47,
	KEY_SCANCODE_RIGHTBRACKET = 48,
	KEY_SCANCODE_BACKSLASH = 49, /**< Located at the lower left of the return
									 *   key on ISO keyboards and at the right end
									 *   of the QWERTY row on ANSI keyboards.
									 *   Produces REVERSE SOLIDUS (backslash) and
									 *   VERTICAL LINE in a US layout, REVERSE
									 *   SOLIDUS and VERTICAL LINE in a UK Mac
									 *   layout, NUMBER SIGN and TILDE in a UK
									 *   Windows layout, DOLLAR SIGN and POUND SIGN
									 *   in a Swiss German layout, NUMBER SIGN and
									 *   APOSTROPHE in a German layout, GRAVE
									 *   ACCENT and POUND SIGN in a French Mac
									 *   layout, and ASTERISK and MICRO SIGN in a
									 *   French Windows layout.
									 */
	KEY_SCANCODE_NONUSHASH = 50, /**< ISO USB keyboards actually use this code
																  *   instead of 49 for the same key, but all
																  *   OSes I've seen treat the two codes
																  *   identically. So, as an implementor, unless
																  *   your keyboard generates both of those
																  *   codes and your OS treats them differently,
																  *   you should generate KEY_SCANCODE_BACKSLASH
																  *   instead of this code. As a user, you
																  *   should not rely on this code because SDL
																  *   will never generate it with most (all?)
																  *   keyboards.
																  */
	KEY_SCANCODE_SEMICOLON = 51,
	KEY_SCANCODE_APOSTROPHE = 52,
	KEY_SCANCODE_GRAVE = 53, /**< Located in the top left corner (on both ANSI
																						   *   and ISO keyboards). Produces GRAVE ACCENT and
																						   *   TILDE in a US Windows layout and in US and UK
																						   *   Mac layouts on ANSI keyboards, GRAVE ACCENT
																						   *   and NOT SIGN in a UK Windows layout, SECTION
																						   *   SIGN and PLUS-MINUS SIGN in US and UK Mac
																						   *   layouts on ISO keyboards, SECTION SIGN and
																						   *   DEGREE SIGN in a Swiss German layout (Mac:
																						   *   only on ISO keyboards), CIRCUMFLEX ACCENT and
																						   *   DEGREE SIGN in a German layout (Mac: only on
																						   *   ISO keyboards), SUPERSCRIPT TWO and TILDE in a
																						   *   French Windows layout, COMMERCIAL AT and
																						   *   NUMBER SIGN in a French Mac layout on ISO
																						   *   keyboards, and LESS-THAN SIGN and GREATER-THAN
																						   *   SIGN in a Swiss German, German, or French Mac
																						   *   layout on ANSI keyboards.
																						   */
	KEY_SCANCODE_COMMA = 54,
	KEY_SCANCODE_PERIOD = 55,
	KEY_SCANCODE_SLASH = 56,

	KEY_SCANCODE_CAPSLOCK = 57,

	KEY_SCANCODE_F1 = 58,
	KEY_SCANCODE_F2 = 59,
	KEY_SCANCODE_F3 = 60,
	KEY_SCANCODE_F4 = 61,
	KEY_SCANCODE_F5 = 62,
	KEY_SCANCODE_F6 = 63,
	KEY_SCANCODE_F7 = 64,
	KEY_SCANCODE_F8 = 65,
	KEY_SCANCODE_F9 = 66,
	KEY_SCANCODE_F10 = 67,
	KEY_SCANCODE_F11 = 68,
	KEY_SCANCODE_F12 = 69,

	KEY_SCANCODE_PRINTSCREEN = 70,
	KEY_SCANCODE_SCROLLLOCK = 71,
	KEY_SCANCODE_PAUSE = 72,
	KEY_SCANCODE_INSERT = 73, /**< insert on PC, help on some Mac keyboards (but
																													 does send code 73, not 117) */
	KEY_SCANCODE_HOME = 74,
	KEY_SCANCODE_PAGEUP = 75,
	KEY_SCANCODE_DELETE = 76,
	KEY_SCANCODE_END = 77,
	KEY_SCANCODE_PAGEDOWN = 78,
	KEY_SCANCODE_RIGHT = 79,
	KEY_SCANCODE_LEFT = 80,
	KEY_SCANCODE_DOWN = 81,
	KEY_SCANCODE_UP = 82,

	KEY_SCANCODE_NUMLOCKCLEAR = 83, /**< num lock on PC, clear on Mac keyboards
																																					 */
	KEY_SCANCODE_KP_DIVIDE = 84,
	KEY_SCANCODE_KP_MULTIPLY = 85,
	KEY_SCANCODE_KP_MINUS = 86,
	KEY_SCANCODE_KP_PLUS = 87,
	KEY_SCANCODE_KP_ENTER = 88,
	KEY_SCANCODE_KP_1 = 89,
	KEY_SCANCODE_KP_2 = 90,
	KEY_SCANCODE_KP_3 = 91,
	KEY_SCANCODE_KP_4 = 92,
	KEY_SCANCODE_KP_5 = 93,
	KEY_SCANCODE_KP_6 = 94,
	KEY_SCANCODE_KP_7 = 95,
	KEY_SCANCODE_KP_8 = 96,
	KEY_SCANCODE_KP_9 = 97,
	KEY_SCANCODE_KP_0 = 98,
	KEY_SCANCODE_KP_PERIOD = 99,

	KEY_SCANCODE_NONUSBACKSLASH = 100, /**< This is the additional key that ISO
																																														*   keyboards have over ANSI ones,
																																														*   located between left shift and Y.
																																														*   Produces GRAVE ACCENT and TILDE in a
																																														*   US or UK Mac layout, REVERSE SOLIDUS
																																														*   (backslash) and VERTICAL LINE in a
																																														*   US or UK Windows layout, and
																																														*   LESS-THAN SIGN and GREATER-THAN SIGN
																																														*   in a Swiss German, German, or French
																																														*   layout. */
	KEY_SCANCODE_APPLICATION = 101, /**< windows contextual menu, compose */
	KEY_SCANCODE_POWER = 102, /**< The USB document says this is a status flag,
																																																				  *   not a physical key - but some Mac keyboards
																																																				  *   do have a power key. */
	KEY_SCANCODE_KP_EQUALS = 103,
	KEY_SCANCODE_F13 = 104,
	KEY_SCANCODE_F14 = 105,
	KEY_SCANCODE_F15 = 106,
	KEY_SCANCODE_F16 = 107,
	KEY_SCANCODE_F17 = 108,
	KEY_SCANCODE_F18 = 109,
	KEY_SCANCODE_F19 = 110,
	KEY_SCANCODE_F20 = 111,
	KEY_SCANCODE_F21 = 112,
	KEY_SCANCODE_F22 = 113,
	KEY_SCANCODE_F23 = 114,
	KEY_SCANCODE_F24 = 115,
	KEY_SCANCODE_EXECUTE = 116,
	KEY_SCANCODE_HELP = 117,
	KEY_SCANCODE_MENU = 118,
	KEY_SCANCODE_SELECT = 119,
	KEY_SCANCODE_STOP = 120,
	KEY_SCANCODE_AGAIN = 121,   /**< redo */
	KEY_SCANCODE_UNDO = 122,
	KEY_SCANCODE_CUT = 123,
	KEY_SCANCODE_COPY = 124,
	KEY_SCANCODE_PASTE = 125,
	KEY_SCANCODE_FIND = 126,
	KEY_SCANCODE_MUTE = 127,
	KEY_SCANCODE_VOLUMEUP = 128,
	KEY_SCANCODE_VOLUMEDOWN = 129,
	/* not sure whether there's a reason to enable these */
	/*     KEY_SCANCODE_LOCKINGCAPSLOCK = 130,  */
	/*     KEY_SCANCODE_LOCKINGNUMLOCK = 131, */
	/*     KEY_SCANCODE_LOCKINGSCROLLLOCK = 132, */
	KEY_SCANCODE_KP_COMMA = 133,
	KEY_SCANCODE_KP_EQUALSAS400 = 134,

	KEY_SCANCODE_INTERNATIONAL1 = 135, /**< used on Asian keyboards, see
																																																													 footnotes in USB doc */
	KEY_SCANCODE_INTERNATIONAL2 = 136,
	KEY_SCANCODE_INTERNATIONAL3 = 137, /**< Yen */
	KEY_SCANCODE_INTERNATIONAL4 = 138,
	KEY_SCANCODE_INTERNATIONAL5 = 139,
	KEY_SCANCODE_INTERNATIONAL6 = 140,
	KEY_SCANCODE_INTERNATIONAL7 = 141,
	KEY_SCANCODE_INTERNATIONAL8 = 142,
	KEY_SCANCODE_INTERNATIONAL9 = 143,
	KEY_SCANCODE_LANG1 = 144, /**< Hangul/English toggle */
	KEY_SCANCODE_LANG2 = 145, /**< Hanja conversion */
	KEY_SCANCODE_LANG3 = 146, /**< Katakana */
	KEY_SCANCODE_LANG4 = 147, /**< Hiragana */
	KEY_SCANCODE_LANG5 = 148, /**< Zenkaku/Hankaku */
	KEY_SCANCODE_LANG6 = 149, /**< reserved */
	KEY_SCANCODE_LANG7 = 150, /**< reserved */
	KEY_SCANCODE_LANG8 = 151, /**< reserved */
	KEY_SCANCODE_LANG9 = 152, /**< reserved */

	KEY_SCANCODE_ALTERASE = 153, /**< Erase-Eaze */
	KEY_SCANCODE_SYSREQ = 154,
	KEY_SCANCODE_CANCEL = 155,
	KEY_SCANCODE_CLEAR = 156,
	KEY_SCANCODE_PRIOR = 157,
	KEY_SCANCODE_RETURN2 = 158,
	KEY_SCANCODE_SEPARATOR = 159,
	KEY_SCANCODE_OUT = 160,
	KEY_SCANCODE_OPER = 161,
	KEY_SCANCODE_CLEARAGAIN = 162,
	KEY_SCANCODE_CRSEL = 163,
	KEY_SCANCODE_EXSEL = 164,

	KEY_SCANCODE_KP_00 = 176,
	KEY_SCANCODE_KP_000 = 177,
	KEY_SCANCODE_THOUSANDSSEPARATOR = 178,
	KEY_SCANCODE_DECIMALSEPARATOR = 179,
	KEY_SCANCODE_CURRENCYUNIT = 180,
	KEY_SCANCODE_CURRENCYSUBUNIT = 181,
	KEY_SCANCODE_KP_LEFTPAREN = 182,
	KEY_SCANCODE_KP_RIGHTPAREN = 183,
	KEY_SCANCODE_KP_LEFTBRACE = 184,
	KEY_SCANCODE_KP_RIGHTBRACE = 185,
	KEY_SCANCODE_KP_TAB = 186,
	KEY_SCANCODE_KP_BACKSPACE = 187,
	KEY_SCANCODE_KP_A = 188,
	KEY_SCANCODE_KP_B = 189,
	KEY_SCANCODE_KP_C = 190,
	KEY_SCANCODE_KP_D = 191,
	KEY_SCANCODE_KP_E = 192,
	KEY_SCANCODE_KP_F = 193,
	KEY_SCANCODE_KP_XOR = 194,
	KEY_SCANCODE_KP_POWER = 195,
	KEY_SCANCODE_KP_PERCENT = 196,
	KEY_SCANCODE_KP_LESS = 197,
	KEY_SCANCODE_KP_GREATER = 198,
	KEY_SCANCODE_KP_AMPERSAND = 199,
	KEY_SCANCODE_KP_DBLAMPERSAND = 200,
	KEY_SCANCODE_KP_VERTICALBAR = 201,
	KEY_SCANCODE_KP_DBLVERTICALBAR = 202,
	KEY_SCANCODE_KP_COLON = 203,
	KEY_SCANCODE_KP_HASH = 204,
	KEY_SCANCODE_KP_SPACE = 205,
	KEY_SCANCODE_KP_AT = 206,
	KEY_SCANCODE_KP_EXCLAM = 207,
	KEY_SCANCODE_KP_MEMSTORE = 208,
	KEY_SCANCODE_KP_MEMRECALL = 209,
	KEY_SCANCODE_KP_MEMCLEAR = 210,
	KEY_SCANCODE_KP_MEMADD = 211,
	KEY_SCANCODE_KP_MEMSUBTRACT = 212,
	KEY_SCANCODE_KP_MEMMULTIPLY = 213,
	KEY_SCANCODE_KP_MEMDIVIDE = 214,
	KEY_SCANCODE_KP_PLUSMINUS = 215,
	KEY_SCANCODE_KP_CLEAR = 216,
	KEY_SCANCODE_KP_CLEARENTRY = 217,
	KEY_SCANCODE_KP_BINARY = 218,
	KEY_SCANCODE_KP_OCTAL = 219,
	KEY_SCANCODE_KP_DECIMAL = 220,
	KEY_SCANCODE_KP_HEXADECIMAL = 221,

	KEY_SCANCODE_LCTRL = 224,
	KEY_SCANCODE_LSHIFT = 225,
	KEY_SCANCODE_LALT = 226, /**< alt, option */
	KEY_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
	KEY_SCANCODE_RCTRL = 228,
	KEY_SCANCODE_RSHIFT = 229,
	KEY_SCANCODE_RALT = 230, /**< alt gr, option */
	KEY_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

	KEY_SCANCODE_MODE = 257,    /**< I'm not sure if this is really not covered
																																																																				 *   by any of the above, but since there's a
																																																																				 *   special KMOD_MODE for it I'm adding it here
																																																																				 */

	/* @} *//* Usage page 0x07 */

	/**
	*  \name Usage page 0x0C
	*
	*  These values are mapped from usage page 0x0C (USB consumer page).
	*/
	/* @{ */

	KEY_SCANCODE_AUDIONEXT = 258,
	KEY_SCANCODE_AUDIOPREV = 259,
	KEY_SCANCODE_AUDIOSTOP = 260,
	KEY_SCANCODE_AUDIOPLAY = 261,
	KEY_SCANCODE_AUDIOMUTE = 262,
	KEY_SCANCODE_MEDIASELECT = 263,
	KEY_SCANCODE_WWW = 264,
	KEY_SCANCODE_MAIL = 265,
	KEY_SCANCODE_CALCULATOR = 266,
	KEY_SCANCODE_COMPUTER = 267,
	KEY_SCANCODE_AC_SEARCH = 268,
	KEY_SCANCODE_AC_HOME = 269,
	KEY_SCANCODE_AC_BACK = 270,
	KEY_SCANCODE_AC_FORWARD = 271,
	KEY_SCANCODE_AC_STOP = 272,
	KEY_SCANCODE_AC_REFRESH = 273,
	KEY_SCANCODE_AC_BOOKMARKS = 274,

	/* @} *//* Usage page 0x0C */

	/**
	*  \name Walther keys
	*
	*  These are values that Christian Walther added (for mac keyboard?).
	*/
	/* @{ */

	KEY_SCANCODE_BRIGHTNESSDOWN = 275,
	KEY_SCANCODE_BRIGHTNESSUP = 276,
	KEY_SCANCODE_DISPLAYSWITCH = 277, /**< display mirroring/dual display
																																																																												   switch, video mode switch */
	KEY_SCANCODE_KBDILLUMTOGGLE = 278,
	KEY_SCANCODE_KBDILLUMDOWN = 279,
	KEY_SCANCODE_KBDILLUMUP = 280,
	KEY_SCANCODE_EJECT = 281,
	KEY_SCANCODE_SLEEP = 282,

	KEY_SCANCODE_APP1 = 283,
	KEY_SCANCODE_APP2 = 284,

	/* @} *//* Walther keys */

	/* Add any other keys here. */

	KEY_NUM_SCANCODES = 512 /**< not a key, just marks the number of scancodes
																																																																																		   for array bounds */
} Key_Scancode;

#define KEY_SCANCODE_MASK (1<<30)
#define SCANCODE_TO_KEYCODE(X)  (X | KEY_SCANCODE_MASK)

enum
{
	KEY_UNKNOWN = 0,

	KEY_RETURN = '\r',
	KEY_ESCAPE = '\033',
	KEY_BACKSPACE = '\b',
	KEY_TAB = '\t',
	KEY_SPACE = ' ',
	KEY_EXCLAIM = '!',
	KEY_QUOTEDBL = '"',
	KEY_HASH = '#',
	KEY_PERCENT = '%',
	KEY_DOLLAR = '$',
	KEY_AMPERSAND = '&',
	KEY_QUOTE = '\'',
	KEY_LEFTPAREN = '(',
	KEY_RIGHTPAREN = ')',
	KEY_ASTERISK = '*',
	KEY_PLUS = '+',
	KEY_COMMA = ',',
	KEY_MINUS = '-',
	KEY_PERIOD = '.',
	KEY_SLASH = '/',
	KEY_0 = '0',
	KEY_1 = '1',
	KEY_2 = '2',
	KEY_3 = '3',
	KEY_4 = '4',
	KEY_5 = '5',
	KEY_6 = '6',
	KEY_7 = '7',
	KEY_8 = '8',
	KEY_9 = '9',
	KEY_COLON = ':',
	KEY_SEMICOLON = ';',
	KEY_LESS = '<',
	KEY_EQUALS = '=',
	KEY_GREATER = '>',
	KEY_QUESTION = '?',
	KEY_AT = '@',
	KEY_LEFTBRACKET = '[',
	KEY_BACKSLASH = '\\',
	KEY_RIGHTBRACKET = ']',
	KEY_CARET = '^',
	KEY_UNDERSCORE = '_',
	KEY_BACKQUOTE = '`',
	KEY_A = 'a',
	KEY_B = 'b',
	KEY_C = 'c',
	KEY_D = 'd',
	KEY_E = 'e',
	KEY_F = 'f',
	KEY_G = 'g',
	KEY_H = 'h',
	KEY_I = 'i',
	KEY_J = 'j',
	KEY_K = 'k',
	KEY_L = 'l',
	KEY_M = 'm',
	KEY_N = 'n',
	KEY_O = 'o',
	KEY_P = 'p',
	KEY_Q = 'q',
	KEY_R = 'r',
	KEY_S = 's',
	KEY_T = 't',
	KEY_U = 'u',
	KEY_V = 'v',
	KEY_W = 'w',
	KEY_X = 'x',
	KEY_Y = 'y',
	KEY_Z = 'z',

	KEY_CAPSLOCK = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CAPSLOCK),

	KEY_F1 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F1),
	KEY_F2 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F2),
	KEY_F3 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F3),
	KEY_F4 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F4),
	KEY_F5 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F5),
	KEY_F6 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F6),
	KEY_F7 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F7),
	KEY_F8 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F8),
	KEY_F9 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F9),
	KEY_F10 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F10),
	KEY_F11 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F11),
	KEY_F12 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F12),

	KEY_PRINTSCREEN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_PRINTSCREEN),
	KEY_SCROLLLOCK = SCANCODE_TO_KEYCODE(KEY_SCANCODE_SCROLLLOCK),
	KEY_PAUSE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_PAUSE),
	KEY_INSERT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_INSERT),
	KEY_HOME = SCANCODE_TO_KEYCODE(KEY_SCANCODE_HOME),
	KEY_PAGEUP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_PAGEUP),
	KEY_DELETE = '\177',
	KEY_END = SCANCODE_TO_KEYCODE(KEY_SCANCODE_END),
	KEY_PAGEDOWN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_PAGEDOWN),
	KEY_RIGHT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_RIGHT),
	KEY_LEFT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_LEFT),
	KEY_DOWN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_DOWN),
	KEY_UP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_UP),

	KEY_NUMLOCKCLEAR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_NUMLOCKCLEAR),
	KEY_KP_DIVIDE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_DIVIDE),
	KEY_KP_MULTIPLY = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MULTIPLY),
	KEY_KP_MINUS = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MINUS),
	KEY_KP_PLUS = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_PLUS),
	KEY_KP_ENTER = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_ENTER),
	KEY_KP_1 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_1),
	KEY_KP_2 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_2),
	KEY_KP_3 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_3),
	KEY_KP_4 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_4),
	KEY_KP_5 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_5),
	KEY_KP_6 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_6),
	KEY_KP_7 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_7),
	KEY_KP_8 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_8),
	KEY_KP_9 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_9),
	KEY_KP_0 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_0),
	KEY_KP_PERIOD = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_PERIOD),

	KEY_APPLICATION = SCANCODE_TO_KEYCODE(KEY_SCANCODE_APPLICATION),
	KEY_POWER = SCANCODE_TO_KEYCODE(KEY_SCANCODE_POWER),
	KEY_KP_EQUALS = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_EQUALS),
	KEY_F13 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F13),
	KEY_F14 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F14),
	KEY_F15 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F15),
	KEY_F16 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F16),
	KEY_F17 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F17),
	KEY_F18 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F18),
	KEY_F19 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F19),
	KEY_F20 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F20),
	KEY_F21 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F21),
	KEY_F22 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F22),
	KEY_F23 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F23),
	KEY_F24 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_F24),
	KEY_EXECUTE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_EXECUTE),
	KEY_HELP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_HELP),
	KEY_MENU = SCANCODE_TO_KEYCODE(KEY_SCANCODE_MENU),
	KEY_SELECT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_SELECT),
	KEY_STOP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_STOP),
	KEY_AGAIN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AGAIN),
	KEY_UNDO = SCANCODE_TO_KEYCODE(KEY_SCANCODE_UNDO),
	KEY_CUT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CUT),
	KEY_COPY = SCANCODE_TO_KEYCODE(KEY_SCANCODE_COPY),
	KEY_PASTE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_PASTE),
	KEY_FIND = SCANCODE_TO_KEYCODE(KEY_SCANCODE_FIND),
	KEY_MUTE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_MUTE),
	KEY_VOLUMEUP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_VOLUMEUP),
	KEY_VOLUMEDOWN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_VOLUMEDOWN),
	KEY_KP_COMMA = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_COMMA),
	KEY_KP_EQUALSAS400 =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_EQUALSAS400),

	KEY_ALTERASE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_ALTERASE),
	KEY_SYSREQ = SCANCODE_TO_KEYCODE(KEY_SCANCODE_SYSREQ),
	KEY_CANCEL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CANCEL),
	KEY_CLEAR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CLEAR),
	KEY_PRIOR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_PRIOR),
	KEY_RETURN2 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_RETURN2),
	KEY_SEPARATOR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_SEPARATOR),
	KEY_OUT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_OUT),
	KEY_OPER = SCANCODE_TO_KEYCODE(KEY_SCANCODE_OPER),
	KEY_CLEARAGAIN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CLEARAGAIN),
	KEY_CRSEL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CRSEL),
	KEY_EXSEL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_EXSEL),

	KEY_KP_00 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_00),
	KEY_KP_000 = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_000),
	KEY_THOUSANDSSEPARATOR =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_THOUSANDSSEPARATOR),
	KEY_DECIMALSEPARATOR =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_DECIMALSEPARATOR),
	KEY_CURRENCYUNIT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CURRENCYUNIT),
	KEY_CURRENCYSUBUNIT =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_CURRENCYSUBUNIT),
	KEY_KP_LEFTPAREN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_LEFTPAREN),
	KEY_KP_RIGHTPAREN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_RIGHTPAREN),
	KEY_KP_LEFTBRACE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_LEFTBRACE),
	KEY_KP_RIGHTBRACE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_RIGHTBRACE),
	KEY_KP_TAB = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_TAB),
	KEY_KP_BACKSPACE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_BACKSPACE),
	KEY_KP_A = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_A),
	KEY_KP_B = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_B),
	KEY_KP_C = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_C),
	KEY_KP_D = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_D),
	KEY_KP_E = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_E),
	KEY_KP_F = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_F),
	KEY_KP_XOR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_XOR),
	KEY_KP_POWER = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_POWER),
	KEY_KP_PERCENT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_PERCENT),
	KEY_KP_LESS = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_LESS),
	KEY_KP_GREATER = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_GREATER),
	KEY_KP_AMPERSAND = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_AMPERSAND),
	KEY_KP_DBLAMPERSAND =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_DBLAMPERSAND),
	KEY_KP_VERTICALBAR =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_VERTICALBAR),
	KEY_KP_DBLVERTICALBAR =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_DBLVERTICALBAR),
	KEY_KP_COLON = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_COLON),
	KEY_KP_HASH = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_HASH),
	KEY_KP_SPACE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_SPACE),
	KEY_KP_AT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_AT),
	KEY_KP_EXCLAM = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_EXCLAM),
	KEY_KP_MEMSTORE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMSTORE),
	KEY_KP_MEMRECALL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMRECALL),
	KEY_KP_MEMCLEAR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMCLEAR),
	KEY_KP_MEMADD = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMADD),
	KEY_KP_MEMSUBTRACT =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMSUBTRACT),
	KEY_KP_MEMMULTIPLY =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMMULTIPLY),
	KEY_KP_MEMDIVIDE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_MEMDIVIDE),
	KEY_KP_PLUSMINUS = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_PLUSMINUS),
	KEY_KP_CLEAR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_CLEAR),
	KEY_KP_CLEARENTRY = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_CLEARENTRY),
	KEY_KP_BINARY = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_BINARY),
	KEY_KP_OCTAL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_OCTAL),
	KEY_KP_DECIMAL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_DECIMAL),
	KEY_KP_HEXADECIMAL =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KP_HEXADECIMAL),

	KEY_LCTRL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_LCTRL),
	KEY_LSHIFT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_LSHIFT),
	KEY_LALT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_LALT),
	KEY_LGUI = SCANCODE_TO_KEYCODE(KEY_SCANCODE_LGUI),
	KEY_RCTRL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_RCTRL),
	KEY_RSHIFT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_RSHIFT),
	KEY_RALT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_RALT),
	KEY_RGUI = SCANCODE_TO_KEYCODE(KEY_SCANCODE_RGUI),

	KEY_MODE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_MODE),

	KEY_AUDIONEXT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AUDIONEXT),
	KEY_AUDIOPREV = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AUDIOPREV),
	KEY_AUDIOSTOP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AUDIOSTOP),
	KEY_AUDIOPLAY = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AUDIOPLAY),
	KEY_AUDIOMUTE = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AUDIOMUTE),
	KEY_MEDIASELECT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_MEDIASELECT),
	KEY_WWW = SCANCODE_TO_KEYCODE(KEY_SCANCODE_WWW),
	KEY_MAIL = SCANCODE_TO_KEYCODE(KEY_SCANCODE_MAIL),
	KEY_CALCULATOR = SCANCODE_TO_KEYCODE(KEY_SCANCODE_CALCULATOR),
	KEY_COMPUTER = SCANCODE_TO_KEYCODE(KEY_SCANCODE_COMPUTER),
	KEY_AC_SEARCH = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_SEARCH),
	KEY_AC_HOME = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_HOME),
	KEY_AC_BACK = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_BACK),
	KEY_AC_FORWARD = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_FORWARD),
	KEY_AC_STOP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_STOP),
	KEY_AC_REFRESH = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_REFRESH),
	KEY_AC_BOOKMARKS = SCANCODE_TO_KEYCODE(KEY_SCANCODE_AC_BOOKMARKS),

	KEY_BRIGHTNESSDOWN =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_BRIGHTNESSDOWN),
	KEY_BRIGHTNESSUP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_BRIGHTNESSUP),
	KEY_DISPLAYSWITCH = SCANCODE_TO_KEYCODE(KEY_SCANCODE_DISPLAYSWITCH),
	KEY_KBDILLUMTOGGLE =
	    SCANCODE_TO_KEYCODE(KEY_SCANCODE_KBDILLUMTOGGLE),
	KEY_KBDILLUMDOWN = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KBDILLUMDOWN),
	KEY_KBDILLUMUP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_KBDILLUMUP),
	KEY_EJECT = SCANCODE_TO_KEYCODE(KEY_SCANCODE_EJECT),
	KEY_SLEEP = SCANCODE_TO_KEYCODE(KEY_SCANCODE_SLEEP)
};

#define BUTTON(X)       (1 << ((X)-1))
#define BUTTON_LEFT     1
#define BUTTON_MIDDLE   2
#define BUTTON_RIGHT    3
#define BUTTON_X1       4
#define BUTTON_X2       5
#define BUTTON_LMASK    BUTTON(BUTTON_LEFT)
#define BUTTON_MMASK    BUTTON(BUTTON_MIDDLE)
#define BUTTON_RMASK    BUTTON(BUTTON_RIGHT)
#define BUTTON_X1MASK   BUTTON(BUTTON_X1)
#define BUTTON_X2MASK   BUTTON(BUTTON_X2)
